backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Price (₹)", name: "price", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }

  - name: "offers"
    label: "Offers"
    folder: "content/offers"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Valid Till", name: "valid_till", widget: "datetime", required: false }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Photo", name: "image", widget: "image" }
